title: Shivang J Trivedi
description: > # this means to ignore newlines until "baseurl:"
  Passionate MECHANICAL engineer having incessant love in TEACHING.
  Sarcastic minded with spiritual nature.
  I have an experience in CNC MILLIMG also proficient in coding the design with G-CODE and M-CODE. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: sjtrivedi31 #if your site has a twitter account, enter it here

# Author Settings
author: Shivang J Trivedi # add your name
author-img: sjtrivedi.jpg # add your photo 
about-author: I am essentially a person with SARCASTIC mind and SPIRITUAL nature.
Perpetually passionate about MECHANICAL TERMS.
Incessant love in teaching. # add description
social-twitter: sjtrivedi31 # add your Twitter handle
social-facebook: ShivAng J TriVedi # add your Facebook handle
social-github: sjtrivedi # add your Github handle
social-linkedin: Shivang J Trivedi # add your Linkedin handle
social-email: sd.trvd3157@gmail.com # add your Email address
social-youtube: UCjPTSAodUFkCMqLrXOFHrug? # youtube
# Disqus
# discus-identifier: mr-strange # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      need_date: false